zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  routes:
    fachref:
      path: /fachref/**
      serviceId: fachref
      sensitive-headers:
    admin:
      path: /admin/**
      serviceId: admin
      sensitive-headers:
    media:
      path: /mediamanagement/**
      url: http://localhost:8083
      sensitive-headers:
    knowledgebase:
      path: /knowledgebase/**
      url: http://localhost:8084
      sensitive-headers:
    bibliometrics:
      path: /bibliometrics/**
      url: http://localhost:8085
      sensitive-headers:
    protokoll:
      path: /protokoll/**
      serviceId: protokoll
    catalogue:
      path: /catalogue/**
      url: http://localhost:8087
      sensitive-headers:
    fileuploader:
      path: /files/**
      serviceId: file-uploader
      sensitive-headers:
    rss:
      path: /rss/**
      serviceId: rssfeeder
      sensitive-headers:
    settings:
      path: /api/settings/**
      serviceId: settings-backend
      sensitive-headers:
    blacklist:
      path: /api/blacklist/**
      serviceId: blacklist-backend
      sensitive-headers:
    scientistdata:
      path: /api/scientistdata/**
      serviceId: knowledgebase-backend
      sensitive-headers:
    servicecatalogue:
      path: /api/servicecatalogue/**
      url: http://localhost:11100
      sensitive-headers:
    data:
      path: /api/data/**
      serviceId: data-backend
      sensitive-headers:
    getter:
      path: /getter/**
      serviceId: getter
      sensitive-headers:
    resources:
      path: /api/resources/**
      serviceId: resources-backend
      sensitive-headers:
    scheduler:
      path: /services/scheduler/**
      ServiceId: scheduler
      sensitive-headers:
    services:
      path: /services/run/**
      serviceId: servicerunner
      sensitive-headers:
    batch:
      path: /services/batch/**
      serviceId: batch
      sensitive-headers:
security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
