server:
  port: ${server_port:8082}
zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  routes:
    fachref:
      path: /fachref/**
      serviceId: fachref
      sensitive-headers:
    admin:
      path: /admin/**
      serviceId: admin
      sensitive-headers:
    media:
      path: /media/**
      serviceId: media
      sensitive-headers:
    knowledgebase:
      path: /knowledgebase/**
      url: http://localhost:8084
      sensitive-headers:
    bibliometrics:
      path: /bibliometrics/**
      url: bibliometrics-backend
      sensitive-headers:
    protokoll:
      path: /protokoll/**
      serviceId: protokoll
      sensitive-headers:
    viewer:
      path: /service/viewer/**
      serviceId: viewer
      sensitive-headers:
    queryexecution:
      path: /bibliometrics/queryExecution
      serviceId: query-execution
      sensitive-headers:
    rss:
      path: /rss/**
      serviceId: rssfeeder
      sensitive-headers:
    settings:
      path: /api/settings/**
      serviceId: settings-backend
      sensitive-headers:
    blacklist:
      path: /api/blacklist/**
      serviceId: blacklist-backend
      sensitive-headers:
    scientistdata:
      path: /api/scientistdata/**
      serviceId: knowledgebase-backend
      sensitive-headers:
    servicecatalogue:
      path: /api/servicecatalogue/**
      url: http://localhost:11100
      sensitive-headers:
    scritping:
      path: /api/scripts/**
      serviceId: scripts
      sensitive-headers:
    data:
      path: /api/data/**
      serviceId: data-backend
      sensitive-headers:
    getter:
      path: /getter/**
      serviceId: getter
      sensitive-headers:
    elisa:
      path: /service/elisa/**
      serviceId: elisa
      sensitive-headers:
    resolver:
      path: /service/linksolver/**
      serviceId: linksolver-wrapper
      sensitive-headers:
    resources:
      path: /api/resources/**
      serviceId: resources-backend
      sensitive-headers:
    services:
      path: /services/run/**
      serviceId: servicerunner
      sensitive-headers:
    batch:
      path: /services/batch/**
      serviceId: batch
      sensitive-headers:
    counterretrieval:
      path: /api/counterretrieval/**
      serviceId: counter-retrieval
      sensitive-headers:
    stockanalyzer:
      path: /api/stockanalyzer/**
      serviceId: stock-analyzer
      sensitive-headers:
    eureka:
      path: /admin/eureka/**
      url: http://localhost:8761
spring:
  security:
    user:
      name: dalek
      password: 3l1m1nat3
  cloud:
    refresh:
      refreshable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    store-type: redis
  application:
    name: gateway
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            lob.non_contextual_creation: true
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
tomcat:
  ajp:
    port: ${ajp_port:8009}
    enabled: true
