zuul:
  routes:
    ui:
      path: /ui/**
      url: http://localhost:3000
      sensitive-headers:
    admin:
      path: /admin/**
      url: http://localhost:8082
      sensitive-headers:
    data:
      path: /resources/data/**
      url: http://localhost:11200
      sensitive-headers:
    getter:
      path: /resources/getter/**
      url: http://localhost/11800
      sensitive-headers:
    fileuploader:
      path: /files/**
      url: http://localhost:11855
      sensitive-headers:
    rss:
      path: /rss/*
      url: http://localhost:11866
      sensitive-headers:
    services:
      path: /services/**
      url: http://locahost:11844
      sensitive-headers:
    batch:
      path: /batch/**
      url: http://localhost:11822
      sensitive-headers:
    settings:
      path: /resources/settings/**
      url: http://localhost:11300
      sensitive-headers:
    blacklist:
      path: blacklist/**
      url: http://localhost:11400
      sensitive-headers:
    resources:
      path: /resources/journals/**
      url: http://localhost:11500
      sensitive-headers:
security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis
  application:
    name: gateway
ribbon:
  eureka:
    enabled: false